catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project hls_packet_receiver
set_top hls_packet_receiver
add_files "/home/sai.divya/pkt_clone/AI_Engine_Development/Feature_Tutorials/04-packet-switching/pktstream_aie/pl_kernels/hls_packet_receiver.cpp"
open_solution -flow_target vitis solution
set_part xcvc1902-vsvd1760-2MP-e-S
# v++ --hls.clock or --kernel_frequency
create_clock -period 250MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_export -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname hls_packet_receiver
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
